bc_user_admin_list:
    pattern:  /
    defaults: { _controller: BcUserAdminBundle:UserAdmin:list }

bc_user_admin_create:
    pattern:  /create
    defaults: { _controller: BcUserAdminBundle:UserAdmin:create }

bc_user_admin_update:
    pattern:  /update/{userId}
    defaults: { _controller: BcUserAdminBundle:UserAdmin:update }

bc_user_admin_delete:
    pattern:  /delete/{userId}
    defaults: { _controller: BcUserAdminBundle:UserAdmin:delete }

bc_user_admin_invite_request_list:
    pattern:  /invite-request
    defaults: { _controller: BcUserAdminBundle:InviteRequestAdmin:list }

bc_user_admin_invite_list:
    pattern:  /invite
    defaults: { _controller: BcUserAdminBundle:Invite:list }

bc_user_admin_invite_create:
    pattern:  /invite/create
    defaults: { _controller: BcUserAdminBundle:Invite:create }

bc_user_admin_invite_batch_create:
    pattern:  /invite/batch-create/{number}
    defaults: { _controller: BcUserAdminBundle:Invite:batchCreate }

bc_user_admin_invite_delete:
    pattern:  /invite/delete/{code}
    defaults: { _controller: BcUserAdminBundle:Invite:delete }
